# syntax = docker/dockerfile:1.2
# not slim because we need github depedencies
FROM sybiote/root-builder as builder

# Create app directory
WORKDIR /app

RUN npm config set registry https://registry.npmjs.org/
RUN npm install --loglevel notice --legacy-peer-deps
# copy then compile the code
COPY . .

ENV APP_ENV=production

FROM node:18-buster-slim as runner
FROM --platform=linux/amd64  python:3.9
WORKDIR /app

RUN apt-get update && apt-get install -y wget gnupg
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends 
RUN rm -rf /var/lib/apt/lists/*

COPY --from=builder /app ./

CMD ["scripts/start-testbot.sh"]